version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=pradeep
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: redis_container
    image: redis
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    
volumes:
  postgres_data:
    
